config:
    line-length: false
    list-marker-space:
        ul_multi: 3
        ul_single: 3
    ul-indent:
        indent: 4
    no-duplicate-header:
        allow_different_nesting: true

noProgress: true

ignores:
    - "**/node_modules/**"
    - apps/cli/tmp
    - .changeset/**
