version: "3.9"

x-database-config: &database-config
    POSTGRES_HOSTNAME: database
    POSTGRES_PORT: "5432"
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_DB: postgres

services:
    validator:
        image: sunodo/rollups-node:0.2.0
        depends_on:
            dapp_deployer:
                condition: service_completed_successfully
        volumes:
            - blockchain-data:/opt/cartesi/share/deployments:ro
            - ./.sunodo/image:/var/opt/cartesi/machine-snapshots/0_0
        healthcheck:
            test: ["CMD", "is_ready"]
            interval: 10s
            timeout: 1s
            retries: 5
        environment:
            # s6-overlay
            S6_VERBOSITY: "${S6_VERBOSITY:-2}"
            # global
            RUST_LOG: "${RUST_LOG:-info}"
            ## shared
            ### redis
            REDIS_ENDPOINT: redis://redis:6379
            ### contract-address-file
            DAPP_CONTRACT_ADDRESS_FILE: /opt/cartesi/share/deployments/dapp.json
            ### session-id
            SESSION_ID: default_session_id
            ### chain-id
            CHAIN_ID: 31337
            TX_CHAIN_ID: 31337
            ### server-manager-endpoint
            SERVER_MANAGER_ENDPOINT: http://localhost:5001
            SERVER_MANAGER_ADDRESS: localhost:5001
            SERVER_MANAGER_LOG_LEVEL: "${SERVER_MANAGER_LOG_LEVEL:-info}"
            REMOTE_CARTESI_MACHINE_LOG_LEVEL: info

            ### database
            <<: *database-config

            # dispatcher
            ## uses redis
            ## uses chain-id (TX_CHAIN_ID acctually)
            RD_DAPP_DEPLOYMENT_FILE: /opt/cartesi/share/deployments/dapp.json
            RD_ROLLUPS_DEPLOYMENT_FILE: /opt/cartesi/share/deployments/localhost.json
            RD_EPOCH_DURATION: "${EPOCH_DURATION:-86400}"
            SC_GRPC_ENDPOINT: http://localhost:50051
            SC_DEFAULT_CONFIRMATIONS: 1
            TX_PROVIDER_HTTP_ENDPOINT: http://anvil:8545
            TX_MNEMONIC: "test test test test test test test test test test test junk"
            TX_CHAIN_IS_LEGACY: ${TX_LEGACY:-false}
            TX_DEFAULT_CONFIRMATIONS: 2

            # state-server
            SF_GENESIS_BLOCK: 0x1
            SF_SAFETY_MARGIN: 1
            BH_HTTP_ENDPOINT: http://anvil:8545
            BH_WS_ENDPOINT: ws://anvil:8545
            BH_BLOCK_TIMEOUT: "${BLOCK_TIMEOUT:-8}"

            # advance-runner
            ## uses redis
            ## uses contract-address-file
            ## uses session-id
            ## uses chain-id
            ## uses server-manager-endpoint
            SNAPSHOT_DIR: "/var/opt/cartesi/machine-snapshots"
            SNAPSHOT_LATEST: "/var/opt/cartesi/machine-snapshots/latest"

            # inspect-server
            ## uses session-id
            ## uses server-manager-endpoint (acctually uses SERVER_MANAGER_ADDRESS)
            INSPECT_SERVER_ADDRESS: 0.0.0.0:5005

            # indexer
            ## uses redis
            ## uses contract-address-file
            ## uses chain-id

            # graphql-server
            ## uses postgres-config
            GRAPHQL_HOST: 0.0.0.0
            GRAPHQL_PORT: 4000

volumes:
    blockchain-data: {}

networks:
    sunodo-controler:
        external: true
