app = "sunodo-api"
primary_region = "ord"

[http_service]
internal_port = 8080
force_https = true

[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250

[env]
PORT = "8080"
WEBSITE_URL = "https://sunodo.io"
AUTH_ISSUER = "https://auth.sunodo.io/"

[deploy]
release_command = "npx prisma migrate deploy"
